services:
  - type: web
    name: smartapp-api
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: DB_HOST
        value: mysql-1ae74dac-emd-980e.d.aivencloud.com
      - key: DB_PORT
        value: "16466"
      - key: DB_USER
        value: avnadmin
      - key: DB_NAME
        value: smart_college
      - key: DB_SSL
        value: "true"
      - key: DB_PASSWORD
        sync: false
