services:
  - type: web
    name: smartapp-api
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: DB_HOST
        value: gateway01.eu-central-1.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: "4000"
      - key: DB_USER
        value: 4H1e8jZ9jkferE2.root
      - key: DB_NAME
        value: smart_college
      - key: DB_SSL
        value: "true"
      - key: DB_SSL_STRICT
        value: "false"
      - key: DB_PASSWORD
        sync: false
