CREATE TABLE IF NOT EXISTS board_comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  b_id INT NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  comment TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (b_id) REFERENCES board(b_id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(uuid) ON DELETE CASCADE
);
